# mochiboot configuration — Nightly edition
# purple-themed for the nightly build flex

TIMEOUT=5
VERBOSE=no
GRAPHICS=yes

# night mode: purple
BRANDING_COLOUR=#825cdc
BRANDING=MochiBoot Nightly

:DEFAULT
    PROTOCOL=linux
    KERNEL_PATH=boot:///vmlinuz-linux
    CMDLINE=root=UUID=%ROOT_UUID% rw loglevel=4

:FALLBACK
    PROTOCOL=linux
    KERNEL_PATH=boot:///vmlinuz-linux
    CMDLINE=root=UUID=%ROOT_UUID% rw loglevel=4
