# mochiboot — boot menu for mochios
# more info: https://github.com/iluxz/mochiboot

TIMEOUT=5
VERBOSE=no
GRAPHICS=yes

# mochi wallpaper
WALLPAPER=boot:///mochiboot/dark.png
WALLPAPER_STYLE=stretched

# mochiboot branding
INTERFACE_BRANDING=MochiBoot
INTERFACE_BRANDING_COLOUR=00aaaa

# terminal colors (mochi dark theme)
TERM_BACKGROUND=00101a80
TERM_FOREGROUND=cdd6f4
TERM_PALETTE=45475a;585b70;f38ba8;a6e3a1;89b4fa;f5c2e7;94e2d5;bac2de
TERM_PALETTE_BRIGHT=585b70;6c7086;f38ba8;a6e3a1;89b4fa;f5c2e7;94e2d5;a6adc8
TERM_MARGIN=2
TERM_MARGIN_GRADIENT=0

INTERFACE_HELP_HIDDEN=no
INTERFACE_HELP_COLOUR=00aa00

:DEFAULT
    PROTOCOL=linux
    KERNEL_PATH=boot:///vmlinuz-linux
    CMDLINE=root=UUID=%ROOT_UUID% rw quiet loglevel=3

:MOCHIOS (recovery mode)
    PROTOCOL=linux
    KERNEL_PATH=boot:///vmlinuz-linux
    CMDLINE=root=UUID=%ROOT_UUID% rw quiet loglevel=3 mochi.recovery

:FALLBACK
    PROTOCOL=linux
    KERNEL_PATH=boot:///vmlinuz-linux
    CMDLINE=root=UUID=%ROOT_UUID% rw quiet loglevel=3
