# mochiboot configuration
# more info: https://github.com/iluxz/mochiboot

TIMEOUT=5

# mochi purple branding
BRANDING_COLOUR=#825cdc
BRANDING=MochiBoot

# graphics
GRAPHICS=yes

# default entry
:DEFAULT
    PROTOCOL=linux
    KERNEL_PATH=boot:///vmlinuz-linux
    CMDLINE=root=UUID=%ROOT_UUID% rw quiet loglevel=3

# fallback kernel
:FALLBACK
    PROTOCOL=linux
    KERNEL_PATH=boot:///vmlinuz-linux
    CMDLINE=root=UUID=%ROOT_UUID% rw quiet loglevel=3
