[Autologin]
User=mochi
Session=plasma.desktop

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
# mochios sddm theme is set by mochios-branding package
