conky.config = {
    alignment = 'bottom_right',
    gap_x = 24,
    gap_y = 20,
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    update_interval = 3600,
    draw_shades = false,
    default_color = '9664c8',
};

conky.text = [[
${font Ubuntu:bold:size=12}${color #9664c8}NIGHTLY BUILD${color}
]];
