# mochios mkinitcpio preset
MODULES=(loop isofs sr_mod ahci ata_piix nvme vboxguest vboxsf vboxvideo)
HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block archiso archiso_loop_mnt filesystems)
