title    mochios install medium (x86_64, UEFI)
sort-key 01
linux    /mochi/boot/x86_64/vmlinuz-linux
initrd   /mochi/boot/x86_64/initramfs-linux.img
options  archisobasedir=mochi archisosearchuuid=%ARCHISO_UUID% quiet loglevel=3 systemd.show_status=false
