name: Public Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Sy --noconfirm archiso base-devel go zstd

      - name: Create builder
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Build mochi
        run: |
          chown -R builder:builder "$PWD"
          cd pkgbuilds/mochi
          export GOTOOLCHAIN=local
          sudo -u builder makepkg -cf --noconfirm --nodeps

      - name: Deploy
        run: |
          cp pkgbuilds/mochi/mochi-*.pkg.tar.zst /tmp/
          cd /tmp
          tar -I zstd -xf mochi-*.pkg.tar.zst
          mkdir -p /repo/os/x86_64
          cp mochi-*.pkg.tar.zst /repo/os/x86_64/
          cp usr/bin/mochi /repo/
          chmod +x /repo/mochi

          cd /repo
          git init
          git config user.name "bot"
          git config user.email "bot@mochios.dev"
          git checkout -b gh-pages
          git add -A
          git commit -m "update"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin gh-pages
